security:
    # 1. Gestion du hachage automatique des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Source de données des utilisateurs (notre entité Students)
    providers:
        app_student_provider:
            entity:
                class: App\Entity\Students
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        # 3. Pare-feu de ton API
        main:
            lazy: true
            provider: app_student_provider
            
            # Intercepte l'authentification soumise en JSON par React
            json_login:
                check_path: api_login
                username_path: email
                password_path: password

            logout:
                path: api_logout
        # config/packages/security.yaml
    access_control:
        - { path: ^/api/students, roles: PUBLIC_ACCESS }
        - { path: ^/api/cvs, roles: PUBLIC_ACCESS }
        - { path: ^/api/jobs, roles: PUBLIC_ACCESS }
        - { path: ^/api/schools, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }