<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602150316 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, website VARCHAR(255) NOT NULL, logo_url VARCHAR(255) NOT NULL, created_at TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cvs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, uploaded_at TIME(0) WITHOUT TIME ZONE NOT NULL, studend_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B9529D90AD7B04 ON cvs (studend_id_id)');
        $this->addSql('CREATE TABLE education (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, school VARCHAR(255) NOT NULL, dates VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, student_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB0A5ED2F773E7CA ON education (student_id_id)');
        $this->addSql('CREATE TABLE experience (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, dates VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, student_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_590C103F773E7CA ON experience (student_id_id)');
        $this->addSql('CREATE TABLE jobs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, duration VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, created_at TIME(0) WITHOUT TIME ZONE NOT NULL, company_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A8936DC538B53C32 ON jobs (company_id_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, student_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEF773E7CA ON project (student_id_id)');
        $this->addSql('CREATE TABLE schools (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, subtitle VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, website VARCHAR(255) NOT NULL, logo_url VARCHAR(255) NOT NULL, created_at TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE skills (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE students (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, year VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, linkedin VARCHAR(255) NOT NULL, github VARCHAR(255) NOT NULL, created_at TIME(0) WITHOUT TIME ZONE NOT NULL, school VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE cvs ADD CONSTRAINT FK_5B9529D90AD7B04 FOREIGN KEY (studend_id_id) REFERENCES students (id)');
        $this->addSql('ALTER TABLE education ADD CONSTRAINT FK_DB0A5ED2F773E7CA FOREIGN KEY (student_id_id) REFERENCES students (id)');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C103F773E7CA FOREIGN KEY (student_id_id) REFERENCES students (id)');
        $this->addSql('ALTER TABLE jobs ADD CONSTRAINT FK_A8936DC538B53C32 FOREIGN KEY (company_id_id) REFERENCES companies (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEF773E7CA FOREIGN KEY (student_id_id) REFERENCES students (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cvs DROP CONSTRAINT FK_5B9529D90AD7B04');
        $this->addSql('ALTER TABLE education DROP CONSTRAINT FK_DB0A5ED2F773E7CA');
        $this->addSql('ALTER TABLE experience DROP CONSTRAINT FK_590C103F773E7CA');
        $this->addSql('ALTER TABLE jobs DROP CONSTRAINT FK_A8936DC538B53C32');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEF773E7CA');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE cvs');
        $this->addSql('DROP TABLE education');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE jobs');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE schools');
        $this->addSql('DROP TABLE skills');
        $this->addSql('DROP TABLE students');
    }
}
